name: BGRemove
description: A Background Remove mobile app

publish_to: 'none' # Remove this line if you plan to publish the app to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.0.0
  introduction_screen: ^2.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/applogo.jpg